name: flutter_m3shapes
description: A collection of Flutter widgets designed to easily implement Material 3's expressive shapes.
version: 1.0.0+2
repository: https://github.com/OrangeRacc00n/flutter_m3shapes

homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  path_drawing: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

